### ISSUE TITLE
AndroidAppRE VM seems to be corrupt or damaged.

### ISSUE THREAD

**Issue by r00tb3** [maddiestone/AndroidAppRE#10]
I've downloaded the `VirtualBox.AndroidAppRE.v2.zip` file as stated by @maddiestone and tried to open the zip file after extracting the  `VirtualBox.AndroidAppRE.v2.zip` but there isn't any zip file inside to open with Virtualbox as stated [here](https://github.com/maddiestone/AndroidAppRE/issues/6#issuecomment-562470931).

Screenshot After downloading and extracting:
![Selection_005](https://user-images.githubusercontent.com/24567198/70386496-1d585e80-19bf-11ea-974b-d29f99d62c69.png)

Inside the AndroidAppRE folder:
![Selection_004](https://user-images.githubusercontent.com/24567198/70386507-42e56800-19bf-11ea-97e3-41740fe64185.png)

If I open the vbox file with VirtualBox I get the following error:
![Selection_007](https://user-images.githubusercontent.com/24567198/70386555-9952a680-19bf-11ea-8aef-2ef8d1a5040e.png)

When I tried to manually open the `VirtualBox.AndroidAppRE.v2.zip` file:
![Selection_006](https://user-images.githubusercontent.com/24567198/70386570-b2f3ee00-19bf-11ea-93f8-543de592bf5c.png)

I don't know what I'm doing wrong or the VM archive is corrupted.

@maddiestone Pls suggest how to resolve this issue.

Regards.

**Comment by maddiestone** [comment]
Just updated the zip file link. Try re-downloading and it should now unzip successfully.
