### ISSUE TITLE
Can the sample apks be provided in the repository

### ISSUE THREAD

**Issue by AayuStark007** [maddiestone/AndroidAppRE#15]
I want to access the sample apks but they are only available in the VM images. 

I tried downloading the VirtualBox VM and the .ova files. But the download always fails with a network error. I've been trying to download the files for last few days without success. 

Without the sample apks, I'm unable to follow the course. 
So, I would like to request the author, or anyone, if they could provide those samples, either as a separate download or by adding them to the repository.

**Comment by stevavoliajvar** [comment]
Yeah that makes sense. Since a lot of us already has the tools setup.

**Comment by stevavoliajvar** [comment]
I uploaded samples [here](https://www.sendspace.com/file/4olj5) if anyone is interested. Also if someone know some better free upload service it should be uploaded there, or just add samples folder to this git repo @maddiestone ?

**Comment by maddiestone** [comment]
Some of the samples are malware. I personally feel it'd be irresponsible to host the sample APKs outside of the VM environment.

**Comment by officialcjunior** [comment]
> I uploaded samples [here](https://www.sendspace.com/file/4olj5) if anyone is interested. Also if someone know some better free upload service it should be uploaded there, or just add samples folder to this git repo @maddiestone ?

The link has expired. 
Can you upload the files again or have it sent to me by some other means? I had all the tools with me, with just needing the samples to work on, too.

**Comment by geekyarthurs** [comment]
you can get the file here. https://github.com/jchristman/MaddieStoneAndroidRE-Docker/tree/1bf57ab8c15daefafaecd6956e15cfb9f0403f0d/samples/ThaiCamera

**Comment by stevavoliajvar** [comment]
@geekyarthurs thanks

**Comment by dramthy** [comment]
@geekyarthurs  nice  job!
