### ISSUE TITLE
Cannot start VM

### ISSUE THREAD

**Issue by n-eq** [maddiestone/AndroidAppRE#6]
Hi,

I have the following issue when trying to start the VM on VirtualBox. Any insights please?

![image](https://user-images.githubusercontent.com/16545838/57984526-e50e2480-7a5c-11e9-8c3c-b8d7e54c6a53.png)

**Comment by MichaelLucas** [comment]
Hello,
I also had an issue with the VM, what is your VirtualBox version? After an upgrade to 6.0.8 it was working fine.

**Comment by n-eq** [comment]
Hello Michael,
Thanks for the reply. I actually have a 5.ish version. 

For future reference, I used VMWare instead and the machine worked fine.

**Comment by maddiestone** [comment]
How are y'all attempting to open the file? You just need to unzip the file then double click on the .vbox file if you have VirtualBox installed. You don't need to do an import. I'm running on 6.0, but others in my in-class workshops have used 5.x. No one had any problems.

**Comment by r00tb3** [comment]
I'm facing same error I'm using VirtualBox 6.0.14 on Ubuntu 18.04 x64.

@maddiestone can you share the thaicamera.apk file as I'm not able to access the VM. 

Regards.

**Comment by maddiestone** [comment]
If you're using VirtualBox, then make sure that you are unzipping and opening the .zip Virtual Box image, not the .ova file. I'm running 6.0.14 on both mac and Ubuntu and it opens just fine.

I've provided the hashes for each sample, but will only be providing the samples through the VMs.
