### ISSUE TITLE
Error importing the VM

### ISSUE THREAD

**Issue by shreyansh26** [maddiestone/AndroidAppRE#9]
On unzipping the .zip file provided for virtualbox, I am getting the following warnings.
![](https://i.imgur.com/uwi49Es.png)

If I ignore them and try opening the vbox file, I get the following error, which is also mentioned in #6 .

![](https://i.imgur.com/v2mTRzQ.png)

Please look into the issue of whether the zip file needs any corrections or suggest any solutions you may have to resolve the issue.

Thanks in advance and also thanks for the amazing course.

**Comment by shreyansh26** [comment]
I am running Ubuntu 16.04 and Virtualbox 5.1.38

**Comment by maddiestone** [comment]
The link should be fixed and the zip file should now work.
